//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeesStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiagnosticCenter.Resources.Views.Employees.EmployeesStrings", typeof(EmployeesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet:.
        /// </summary>
        public static string Cabinet {
            get {
                return ResourceManager.GetString("Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose cabinet.
        /// </summary>
        public static string ChooseCab {
            get {
                return ResourceManager.GetString("ChooseCab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose department.
        /// </summary>
        public static string ChooseDept {
            get {
                return ResourceManager.GetString("ChooseDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose position.
        /// </summary>
        public static string ChoosePosition {
            get {
                return ResourceManager.GetString("ChoosePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Employee Registering.
        /// </summary>
        public static string CreateEmployee {
            get {
                return ResourceManager.GetString("CreateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department chief doctor.
        /// </summary>
        public static string departmentchief {
            get {
                return ResourceManager.GetString("departmentchief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s Information Editing.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Empl {
            get {
                return ResourceManager.GetString("Empl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find employee.
        /// </summary>
        public static string FindEmployee {
            get {
                return ResourceManager.GetString("FindEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head doctor.
        /// </summary>
        public static string headdoctor {
            get {
                return ResourceManager.GetString("headdoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head nurse.
        /// </summary>
        public static string headnurse {
            get {
                return ResourceManager.GetString("headnurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours per month.
        /// </summary>
        public static string HoursPerDay {
            get {
                return ResourceManager.GetString("HoursPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about Employee .
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurse.
        /// </summary>
        public static string nurse {
            get {
                return ResourceManager.GetString("nurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        public static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar.
        /// </summary>
        public static string registar {
            get {
                return ResourceManager.GetString("registar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by surname.
        /// </summary>
        public static string SearchBySurname {
            get {
                return ResourceManager.GetString("SearchBySurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty:.
        /// </summary>
        public static string Specialty {
            get {
                return ResourceManager.GetString("Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
    }
}
