//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiagnosticCenter.Resources.Views.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add cabinet.
        /// </summary>
        public static string AddCabinet {
            get {
                return ResourceManager.GetString("AddCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add department.
        /// </summary>
        public static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add News.
        /// </summary>
        public static string AddNews {
            get {
                return ResourceManager.GetString("AddNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add patient.
        /// </summary>
        public static string AddPatient {
            get {
                return ResourceManager.GetString("AddPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pattern.
        /// </summary>
        public static string AddPattern {
            get {
                return ResourceManager.GetString("AddPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cabinets.
        /// </summary>
        public static string AllCabinets {
            get {
                return ResourceManager.GetString("AllCabinets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All departments.
        /// </summary>
        public static string AllDepartments {
            get {
                return ResourceManager.GetString("AllDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All employees.
        /// </summary>
        public static string AllEmployees {
            get {
                return ResourceManager.GetString("AllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All News.
        /// </summary>
        public static string AllNews {
            get {
                return ResourceManager.GetString("AllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All patients.
        /// </summary>
        public static string AllPatients {
            get {
                return ResourceManager.GetString("AllPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All patterns.
        /// </summary>
        public static string AllPatterns {
            get {
                return ResourceManager.GetString("AllPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinets.
        /// </summary>
        public static string Cabinets {
            get {
                return ResourceManager.GetString("Cabinets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination patterns.
        /// </summary>
        public static string ExaminationPatterns {
            get {
                return ResourceManager.GetString("ExaminationPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Employee.
        /// </summary>
        public static string FindEmployee {
            get {
                return ResourceManager.GetString("FindEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find patient.
        /// </summary>
        public static string FindPatient {
            get {
                return ResourceManager.GetString("FindPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chernivtsi Diagnostic Center.
        /// </summary>
        public static string Headline {
            get {
                return ResourceManager.GetString("Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide menu.
        /// </summary>
        public static string HideMenu {
            get {
                return ResourceManager.GetString("HideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule2 {
            get {
                return ResourceManager.GetString("Schedule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcomе.
        /// </summary>
        public static string Welcomе {
            get {
                return ResourceManager.GetString("Welcomе", resourceCulture);
            }
        }
    }
}
